### PR TITLE
Add assertfatal

### PR DESCRIPTION
**Pull request by lifenod**

### CODE REVIEW

**Comment by xuxinx** [comment]
LGTM :)

**Comment by lifenod** [comment]
By the way, I don't think [assert.EqualAndFatal](https://github.com/theplant/testingutils/blob/3a5dff136cafd318c423b087e59bd80e2f0b29c5/assert/assert.go#L46) has any ambiguity.

For example, Node.js `assert.equal(actual, expected[, message])` https://nodejs.org/api/assert.html#assert_assert_equal_actual_expected_message ,
assert equal mean if not equal then fatal, not if equal then fatal.
For Ruby, https://ruby-doc.org/stdlib-2.1.1/libdoc/test/unit/rdoc/Test/Unit/Assertions.html#method-i-assert_equal

**Comment by xuxinx** [comment]
In my understanding, function in assert package is to assert the actual and the expected meet some conditions just as the function name, like `equal`, `notEqual`, `bigAndRed`. So `assert.EqualAndFatal` really confused me, but to think it as `assert A and B are equal, if they are, then fatal`.

**Comment by lifenod** [comment]
For "assert a and b are equal", mean I expect a and b are equal, so if they are not equal then fatal, it's true in any language,

**Comment by tnclong** [comment]
Let's follow other famous packages names.
Like Linux commands that `-r -f -d -l`, you only need to study ones and guss what them meaning.

**Comment by lifenod** [comment]
> Let's follow other famous packages names.
Like Linux commands that -r -f -d -l, you only need to study ones and guss what them meaning.

But in assert package, you don't need to guess, it's clear.

**Comment by lifenod** [comment]
`assert.IfEqualThenFatal()` is more confused, I guess you like `if.IfEqualThenFatal()`.

**Comment by lifenod** [comment]
@tnclong the new package `assertfatal` is ok?

**Comment by tnclong** [comment]
> if

`if` is a keyword.

> the new package assertfatal is ok?

You mean we have both of `assertfatal` and `assert` packages ?
Do you think it will worse than current only have one package?

**Pull request merged**
